# Full reference: https://docs.airplane.dev/tasks/task-definition

slug: approve_comment
name: Approve comment
parameters:
  - name: Comment ID
    slug: comment_id
    type: integer
    required: false

sql:
  resource: dev_comments
  entrypoint: approve_comment.sql
  queryArgs:
    comment_id: "{{params.comment_id}}"
